export const RESET_FILTERS = 'RESET_FILTERS';
export const SET_BRAND_FILTER = 'SET_BRAND_FILTER';
export const SET_CATEGORY_FILTER = 'SET_CATEGORY_FILTER';
export const SET_SUB_CATEGORY_FILTER = 'SET_SUB_CATEGORY_FILTER';