export const RESET_FILTERS = 'RESET_FILTERS';
export const SET_BRAND_FILTER = 'SET_BRAND_FILTER';
export const SET_CATEGORY_FILTER = 'SET_CATEGORY_FILTER';
export const SET_SUB_CATEGORY_FILTER = 'SET_SUB_CATEGORY_FILTER';

export const SET_DESCRIPTION_FILTER = 'SET_DESCRIPTION_FILTER';
export const SET_MODEL_ID_FILTER = 'SET_MODEL_ID_FILTER';
export const SET_SKU_FILTER = 'SET_SKU_FILTER';
export const SET_UPC_FILTER = 'SET_UPC_FILTER';
// export const SET_MSRP_FILTER = 'SET_MSRP_FILTER';
export const SET_SIZE_FILTER = 'SET_SIZE_FILTER';
export const SET_COLOR_FILTER = 'SET_COLOR_FILTER';
export const SET_SPEED_FILTER = 'SET_SPEED_FILTER';
