export const RESET_FILTERS = 'RESET_FILTERS';
export const SET_BRAND_FILTER = 'SET_BRAND_FILTER';
export const SET_CATEGORY_FILTER = 'SET_CATEGORY_FILTER';
export const SET_SUB_CATEGORY_FILTER = 'SET_SUB_CATEGORY_FILTER';

export const SET_DESCRIPTION_FILTER = 'SET_DESCRIPTION_FILTER';
export const SET_MODEL_ID_FILTER = 'SET_MODEL_ID_FILTER';
export const SET_SKU_FILTER = 'SET_SKU_FILTER';
export const SET_BARCODE_FILTER = 'SET_BARCODE_FILTER';
export const SET_PART_NUM_FILTER = 'SET_PART_NUM_FILTER';
