# GET http://localhost:6969/api/products

# GET http://localhost:6969/api/taxonomy_vendor

# GET http://localhost:6969/api/products', { brandFilter: {value: 'Trek'} }



























































